# Generated by Django 4.1.2 on 2022-11-07 12:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_cont_me'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
