# Generated by Django 4.1.2 on 2022-11-07 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_item_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='datetime',
            new_name='dtime',
        ),
    ]
