# Generated by Django 4.1.2 on 2022-11-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_datetime_item_dtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='dtime',
            field=models.DateTimeField(null=True),
        ),
    ]
