# Generated by Django 4.1.2 on 2022-11-07 15:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_item_seller_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='current_bidder_name',
            field=models.TextField(default=django.utils.timezone.now, max_length=191),
            preserve_default=False,
        ),
    ]
